#!/bin/bash

cd ~/storage/downloads/Madison\ Place/

echo $1 >> test.txt
echo Checking available resolutions...
echo 
/data/data/com.termux/files/usr/bin/python /data/data/com.termux/files/usr/bin/ytdl $1

echo
echo Please choose the file you want to download:
echo "(enter 0 to download using youtube-dl)"
read  selected_file

if [ $selected_file = "0" ]
then
	echo
	echo Running: youtube-dl $1
	/data/data/com.termux/files/usr/bin/python /data/data/com.termux/files/usr/bin/youtube-dl $1
else
	echo
	echo Running: ytdl -n$selected_file $1
	/data/data/com.termux/files/usr/bin/python /data/data/com.termux/files/usr/bin/ytdl -n $selected_file $1
fi
